pipeline:
  name: DemoCD pipeline
  identifier: DemoCD_pipeline
  projectIdentifier: SampleProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy CD
        identifier: Deploy_CD
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: Service_1
            serviceDefinition:
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: manifestCD
                      type: K8sManifest
                      spec:
                        store:
                          type: Git
                          spec:
                            connectorRef: GitKubeWebsiteConnector
                            gitFetchType: Branch
                            paths:
                              - content/en/examples/application/nginx-app.yaml
                            repoName: website
                            branch: main
                        skipResourceVersioning: false
              type: Kubernetes
          infrastructure:
            environmentRef: Devlopement_environment
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: harnessnadeem
                namespace: harness-delegate-ng
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
